# Week 2

In [1]:
import numpy as np
from scipy import stats
import pandas as pd
from sympy import *

## Week 2-1
### Approximation method 1
 When the random variable $X$ follows $\mathcal{B}(n,p)$,  $\hat{p}^∗ = \frac{X+0.5}{n+1}$ follows $\mathcal{N}(p, \frac{p(1-p)}{n})$
 in a similar way.
### Approximation method 2
Let $L$ be a function $L(x)=\rm{ln}\frac{x}{1-x}$. The transformation of numbers by thisfunction is called the **logit transformation**.  
When the random variable $X$ follows $\mathcal{B}(n,p)$,  $L(\mathcal{B}(n,p))$ follows approximately $\mathcal{N}(L(p), \frac{1}{np(1-p)})$

In [6]:
def approx_1(n, p0, X):
    p_hat = (X + 0.5) / (n + 1)
    U0 = (p_hat - p0) / np.sqrt(p0 * (1 - p0) / n)
    return U0


def logit_transform(p):
    assert 0 < p < 1
    return np.log(p / (1-p))


def approx_2(n, p0, X):
    p_hat = (X + 0.5) / (n + 1)
    Lp_hat = logit_transform(p_hat)
    Lp_0 = logit_transform(p0)
    U0 = (Lp_hat - Lp_0) * np.sqrt(n * p0 * (1 - p0))
    return U0

In [29]:
# n, X, p0 = 20, 11, 1/3
# alpha = 0.01

n, X, p0 = 500, 20, 0.05
alpha = 0.05

U_01 = approx_1(n, p0, X)
U_02 = approx_2(n, p0, X)
print("Approximation method 1 = {:.3f}, Approximation method 2 = {:.3f}".format(U_01, U_02))

Approximation method 1 = -0.932, Approximation method 2 = -1.023


### Estimation of the parameters of binomial distribution
Estimate the parameter (population) $p$ of the binomial distribution.  
There are two types of parameter estimation: point estimation and interval estimation.   
For point estimation, $\hat{p}=\frac{X}{n}$ or $\hat{p}^∗=\frac{X+0.5}{n+1}$ is used as the estimator. 
$$
\rm{Pr}\left\{z(\frac{\alpha}{2})≤U_0≤z(1−\frac{\alpha}{2})\right\}\approx 1−\alpha
$$

In [33]:
# Calculate the rejection region
n_statistic = stats.norm.ppf(1 - alpha/2)
print("rejection region statistic={:.3f}".format(n_statistic))
alpha_half = alpha / 2
n_statistic_left = stats.norm.ppf(alpha_half)
n_statistic_right = stats.norm.ppf(1 - alpha_half)
lambda_hs = (X + 0.5) / (n + 1)

# Method 1
var = np.sqrt(lambda_hs * (1 - lambda_hs) / n)
lower_interval1 = n_statistic_left * var + lambda_hs
upper_interval1 = n_statistic_right * var + lambda_hs
print("Method 1 Interval=({:.3f}, {:.3f})".format(lower_interval1, upper_interval1))

# Method 2
Lp_hs = logit_transform(lambda_hs)
var = 1 / np.sqrt(n * lambda_hs * (1 - lambda_hs))
lower_interval2 = 1 / (1 + np.exp(-(n_statistic_left * var + Lp_hs)))
upper_interval2 = 1 / (1 + np.exp(-(n_statistic_right * var + Lp_hs)))

print("Method 2 Interval=({:.3f}, {:.3f})".format(lower_interval2, upper_interval2))

rejection region statistic=1.960
Method 1 Interval=(0.024, 0.058)
Method 2 Interval=(0.027, 0.062)


## Week 2-2
- **Approximation method 1**  
 When the random variable $W$ follows $Po(\lambda)$, $\hat{p}^∗ = \frac{X+0.5}{n+1}$ follows $\mathcal{N}(p, \frac{p(1-p)}{n})$
 in a similar way.  
- **Approximation method 2**  
Let $L$ be a function $L(x)=\rm{ln}\frac{x}{1-x}$. The transformation of numbers by thisfunction is called the **logit transformation**.  
When the random variable $X$ follows $\mathcal{B}(n,p)$,  $L(\mathcal{B}(n,p))$ follows approximately $\mathcal{N}(L(p), \frac{1}{np(1-p)})$

In [4]:
def po_approx_1(n, W, lambda_0):
    lambda_hs = (W + 0.5) / n
    U0 = (lambda_hs - lambda_0) / np.sqrt(lambda_0 / n)
    return U0


def po_approx_2(n, W, lambda_0):
    lambda_hs = (W + 0.5) / n
    U0 = (np.log(lambda_hs) - np.log(lambda_0)) * np.sqrt(n * lambda_0)
    return U0

In [5]:
# exercise 2-2
n, W, lambda_0 = 9986, 121, 0.01
alpha = 0.05

U_01 = po_approx_1(n, W, lambda_0)
U_02 = po_approx_2(n, W, lambda_0)
print("Approximation method 1 = {:.3f}, Approximation method 2 = {:.3f}".format(U_01, U_02))

Approximation method 1 = 2.166, Approximation method 2 = 1.960


Parameter estimation of Poisson distribution
There are two types of parameter estimation: point estimation and interval estimation.  
For point estimation, $\hat{λ} = W$ or $\hat{λ}^∗ = \frac{W+0.5}{n}$ is used as estimators.

In [13]:
# Calculate the rejection region
n_statistic = stats.norm.ppf(1 - alpha)
print("rejection region statistic={:.3f}".format(n_statistic))
alpha_half = alpha / 2

n_statistic_left = stats.norm.ppf(alpha_half)
n_statistic_right = stats.norm.ppf(1 - alpha_half)
lambda_hs = (W + 0.5) / n

# Method 1
var = np.sqrt(lambda_hs / n)
lower_interval1 = n_statistic_left * var + lambda_hs
upper_interval1 = n_statistic_right * var + lambda_hs
print("Method 1 Interval=({:.3f}, {:.3f})".format(lower_interval1, upper_interval1))

# Method 2
ln_lambda = np.log(lambda_hs)
var = 1 / np.sqrt(n * lambda_hs)
lower_interval2 = np.exp(n_statistic_left * var + ln_lambda)
upper_interval2 = np.exp(n_statistic_right * var + ln_lambda)

print("Method 2 Interval=({:.3f}, {:.3f})".format(lower_interval2, upper_interval2))

rejection region statistic=1.645
Method 1 Interval=(0.010, 0.014)
Method 2 Interval=(0.010, 0.015)


## Week 2-3
Test and Estimate on the Population Correlation Coefficients

In [28]:
def approx_t0(R, n):
    return (R * np.sqrt(n - 2)) / np.sqrt(1 - R * R)

def approx_z(R):
    return 0.5 * np.log((1 + R) / (1 - R))

def read_from_excel(file_path):
    df = pd.read_excel(file_path)
    columns_data = {col: df[col].values for col in df.columns}
    A = columns_data[df.columns[1]]
    B = columns_data[df.columns[2]]
    A = A[~np.isnan(A)]
    B = B[~np.isnan(B)]
    return A, B

In [32]:
A, B = read_from_excel('mini-exam2-3.xlsx')
correlation_matrix = np.corrcoef(A, B)
R, n = correlation_matrix[0, 1], len(A)

df = n - 2
t0 = approx_t0(R, n)

alpha = 0.05
alpha_half = alpha / 2
t_statistic = stats.t.ppf(1 - alpha, df)

print("Sample Correlation Coefficient R = {:.3f}, number of samples n = {}".format(R, n))
print("t-stat approximation = {:.3f}".format(t0))
print("rejection region statistic = {:.3f}".format(t_statistic))

Sample Correlation Coefficient R = 0.795, number of samples n = 50
t-stat approximation = 9.081
rejection region statistic = 1.677


### Estimation of Population Correlation Coefficient
Estimate population correlation coefficient $ρ$.  
There are two types of parameter estimation: point estimation and interval estimation.   
- For point estimation, $\hat{p}=R$. 
- For interval estimation, we use the fact that $Z=\frac{1}{2}{\rm ln}\frac{1+R}{1-R}$ approximately follows $\mathcal{N}(\frac{1}{2}{\rm ln}\frac{1+ρ}{1-ρ}, \frac{1}{n-3})$ when $\rho \neq 0$.   
$$
{\rm Pr}\left\{z(\frac{\alpha}{2})≤\frac{Z-\frac{1}{2}{\rm ln}\frac{1+ρ}{1-ρ}}{\sqrt{\frac{1}{n-3}}}≤z(1−\frac{\alpha}{2})\right\}\approx 1−\alpha
$$
When $\zeta=\frac{1}{2}{\rm ln}\frac{1+ρ}{1-ρ}$ is used, 
$$
{\rm Pr}\left\{Z - z(1−\frac{\alpha}{2})\sqrt{\frac{1}{n-3}} \leq 
\zeta \leq Z-z(\frac{\alpha}{2})\sqrt{\frac{1}{n-3}}\right\}\approx 1−\alpha
$$
Then we get   
 $$\rho=\frac{e^{2\zeta-1}}{e^{2\zeta+1}}$$


In [33]:
Z = 0.5 * np.log((1 + R) / (1 - R))
n_statistic_left = stats.norm.ppf(alpha_half)
n_statistic_right = stats.norm.ppf(1 - alpha_half)

def transform_to_coeff(zeta):
    return (np.exp(2*zeta) - 1) / (np.exp(2*zeta) + 1)

zeta1 = Z - n_statistic_right / np.sqrt(n - 3)
zeta2 = Z - n_statistic_left / np.sqrt(n - 3)

rho1 = transform_to_coeff(zeta1)
rho2 = transform_to_coeff(zeta2)
print("confidence interval for ρ is ({:.3f}, {:.3f})".format(rho1, rho2))

confidence interval for ρ is (0.664, 0.879)


In [38]:
# Video 2-4
df = pd.read_excel('2-4_Test on Contingency Table.xlsx', index_col=0)

expected_table, table = {}, []
for col in df.columns:
    value_counts = df[col].value_counts().to_dict()
    expected_table[col] = value_counts
    print(f"{col} = {value_counts}")

A, B = expected_table[df.columns[0]], expected_table[df.columns[1]]
keys = sorted(A.keys())  # 获取所有键并排序
A_values = [A[k] for k in keys]  # 按照排序的键顺序提取A的值
B_values = [B[k] for k in keys]  # 按照排序的键顺序提取B的值

table = [A_values, B_values]
table = np.array(table)
print(table)

sum_prod = np.sum(table, axis=1)
sum_grade = np.sum(table, axis=0)

expected_tab = np.mean(table, axis=0, keepdims=True)
print(expected_tab)

diff = (table - expected_tab)**2 / expected_tab
chi = np.sum(diff)
alpha = 0.05
df = (table.shape[0] - 1) * (table.shape[1] - 1)
chi_inv = stats.chi2.ppf(1 - alpha, df)
print("X^2 test statistic = {:.3f}, degree of freedom = {}".format(chi, df))
print("rejection region = {:.3f}".format(chi_inv))

Machine A (grade) = {1: 55, 2: 40, 3: 5}
Machine B (grade) = {1: 68, 3: 22, 2: 10}
[[55 40  5]
 [68 10 22]]
[[61.5 25.  13.5]]
X^2 test statistic = 30.078, degree of freedom = 2
rejection region = 5.991


In [65]:
# Mini-Exam 2-4
contingency_table = np.array([[66, 38, 46], [72, 36, 42], [93, 39, 18]])
row_sums = np.sum(contingency_table, axis=1)
col_sums = np.sum(contingency_table, axis=0)
total_sums = np.sum(contingency_table)
expected_table = np.empty_like(contingency_table)

# 计算新数组中的每个元素
for i in range(expected_table.shape[0]):
    for j in range(expected_table.shape[1]):
        expected_table[i, j] = row_sums[i] * col_sums[j] / total_sums

diff = (table - expected_tab) **2 / expected_tab
chi = np.sum(diff)
alpha = 0.05
df = (table.shape[0] - 1) * (table.shape[1] - 1)
chi_inv = stats.chi2.ppf(1 - alpha, df)

print("expected_table:")
print(expected_table)
print("sum rows = {}".format(row_sums))
print("sum columns = {}".format(col_sums))
print("X^2 test statistic = {:.3f}\ndegree of freedom = {}".format(chi, df))
print("rejection region = {:.3f}".format(chi_inv))

expected_table:
[[77 37 35]
 [77 37 35]
 [77 37 35]]
sum rows = [150 150 150]
sum columns = [231 113 106]
X^2 test statistic = 2.381
degree of freedom = 1
rejection region = 3.841
